# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build golang project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build go cube
      run: go build Golang/cube.go

    - name: Build c++ cube
      run: g++ -o cube C++/cube.cpp -Wall
  
    - name: Build c cube
      run: gcc -o cube C/cube.cpp -Wall
